### PR TITLE
Add role field to user model

### PR DESCRIPTION
**Pull request by utdemir**
Roles
1. student
2. teacher

Rules
- All user will be student after register.
- Admin can change user role to teacher.

Methods
- Define `current_role` method to application_controllers.rb

### CODE REVIEW

**Comment by utdemir** [comment]
I intend to start with this issue and suggest using [enumerize](https://github.com/brainspec/enumerize) gem if everyone approves.

**Comment by onurozgurozkan** [comment]
@utdemir +1 for enumerize. 
@muhammetdilek what do you think? Add a role table or enumerize gem for saving users' role.

**Comment by halit** [comment]
Maybe we should just numbers for it? For example; Admin=0, Student=1, Teacher=2 etc. I think it is not necessary to use gem.

**Comment by hamitturkukaya** [comment]
+1 for enumerize

**Comment by armankara** [comment]
+1 for enumerize

2013/9/10 Onur Özgür ÖZKAN notifications@github.com

> Roles
> 1. student
> 2. teacher
> 
> Rules
> - All user will be student after register.
> - Admin can change user role to teacher.
> 
> Methods
> - Define current_role method to application_controllers.rb
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/yakut-project/yakut/issues/26
> .

## 

info@armankara.com
www.armankara.com
Arman Kara
Adobe Flash Professional Certified Expert

**Comment by onurozgurozkan** [comment]
@halitalptekin Numbers are not good idea. If we use numbers, we should redesign forms, validations, etc etc.

By the way if we use numbers, we can use bitmask. 
- http://railscasts.com/episodes/189-embedded-association?view=asciicast

**Comment by marjinal1st** [comment]
:+1: for enumerize.

@halitalptekin We used this gem for genders in summer camp project. It's deadly easy and useful :) You can check it out:

https://github.com/yakut-project/yakut-old/blob/develop/app/models/user.rb

**Comment by halit** [comment]
@marjinal1st I saw your solution and like it.But my idea like this;

https://github.com/yakut-project/kozalak/blob/develop/app/models/user.rb

**Comment by utdemir** [comment]
@halitalptekin But enumerize gem also provides methods like "#male?", and allows expressions like "user.gender = :male"

**Comment by adamdilek** [comment]
@onurozgurozkan enumerize is great idea.

**Comment by utdemir** [comment]
I think using strings as enumeration keys kills the whole idea, it's no different then just using strings and validations. But instead we can achieve the same result using scopes. If I add `scope: true` in model, the call:

```
User.with_role :user
```

is automatically translates to:

```
User Load (0.3ms)  SELECT "users".* FROM "users" WHERE "users"."role" = 1
```

**Comment by onurozgurozkan** [comment]
I am not sure. I looked at [gem example](https://github.com/brainspec/enumerize#usage), they also use number but I don't like integer for these case. :)

Should we need keys? Why don't we just use values?

`enumerize :role, in: [:user, :teacher], default: :user`

**Comment by utdemir** [comment]
As far as I know, {user: 0, teacher: 1} and [:user, :teacher] is equilevent, the former one just lets us to specify equilevent integers explicitly.

**Comment by utdemir** [comment]
Hey guys!

What's up? I hope everyone is fine.

I have a little request; can someone close this PR? It's on my open pull requests list for more than two years and it started to bother me a bit :). Probably because I left the Yakut organisation, I don't have the right to close this issue.

Thank you for all your efforts, I remember that this project was a pretty nice experience.

**Pull request closed without merging**
